### ISSUE TITLE
Java Microservices

### ISSUE THREAD

**Issue by cassiosantana** [cassiosantana/Java-Study#14]
# Java Microservices with Spring Boot and Spring Cloud

Feign, Ribbon, Hystrix, OAuth, JWT, Discovery Server Eureka, API Gateway Zuul, Config Server, and more
@acenelio [course](https://www.udemy.com/course/java-curso-completo/)

### Introduction

- [ ] Course overview
- [ ] The system we are going to develop
- [ ] Introduction to microservices
- [ ] Course prerequisites
- [ ] WARNING: use Spring Boot version 2.3.x
- [ ] Course github
- [ ] Downloading and running the finished project

### Phase 1: Simple Communication, Feign, Ribbon

- [ ] WARNING: Create the projects in Spring Boot version 2.3
- [ ] Creating hr-worker project and starting Git monorepo
- [ ] Implementing hr-worker project
- [ ] Creating hr-payroll project
- [ ] Implementing hr-payroll project with mock
- [ ] RestTemplate
- [ ] Feign client
- [ ] Load Balancing with Ribbon

### Phase 2: Eureka, Hystrix, Zuul

- [ ] Creating hr-eureka-server project
- [ ] Configuring Eureka server
- [ ] Configuring Eureka Clients
- [ ] Random port for hr-worker
- [ ] Hystrix for fault tolerance
- [ ] Creating hr-api-gateway-zuul project
- [ ] Configuring Zuul api gateway
- [ ] Random port for hr-payroll
- [ ] Zuul timeout

### Phase 3: Centralized Configuration

- [ ] Creating hr-config-server project
- [ ] Configuring hr-config-server project
- [ ] hr-worker as configuration server client
- [ ] Actuator to update settings at runtime
- [ ] Private Git repository

### Phase 4: Authentication and Authorization

- [ ] Authentication and Authorization
- [ ] Creating hr-user project
- [ ] Setting up hr-user project
- [ ] User, Role, many-to-many association
- [ ] Initial database load (seeding)
- [ ] UserRepository, UserResource, Zuul config
- [ ] Creating hr-oauth project
- [ ] Configuring hr-oauth project
- [ ] UserFeignClient
- [ ] Login and JWT token PART 1/2
- [ ] Login and JWT token PART 2/2
- [ ] Authorization by Zuul
- [ ] Leaving Postman top
- [ ] Security settings on the configuration server
- [ ] CORS configuration

### Creating and testing Docker containers

Docker installed
WARNING: changing branch in Git
WARNING: Github-centric settings
Tuning hr-user and hr-worker services
Chapter support material
Creating Docker hr-net network
Running hr-worker on profile dev with Postgres
Running hr-user on profile dev with Postgres
Changing references to containers
hr-config-server container
hr-eureka-server container
hr-worker container
hr-user container
hr payroll container
hr-oauth container
hr-api-gateway-zuul Container
Scaling instances of a container
Testing everything
